version: '3.8'

services:
  python-scheduler:
    build: .
    container_name: python-tasks
    environment:
      - TIMEZONE=${TIMEZONE:-Asia/Shanghai}              # 时区设置
      - LOG_LEVEL=${LOG_LEVEL:-INFO}                     # 日志级别
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    restart: unless-stopped
    # 网络配置（如果需要连接其他服务）
    # networks:
    #   - py-network
    # 端口映射（如果需要端口，取消注释）
    # ports:
    #   - "24000:24000"
    #   - "24001:24001"
    #   - "24002:24002"
    #   - "24003:24003"
    #   - "24004:24004"
    #   - "24005:24005"
    #   - "24006:24006"
    #   - "24007:24007"
    #   - "24008:24008"
    #   - "24009:24009"
    #   - "24010:24010"

# 如果需要自定义网络，取消注释
# networks:
#   cron-network:
#     driver: bridge

# 如果需要命名卷，取消注释
# volumes:
#   cron-data:
#   cron-logs: